# Generated by Django 3.0.2 on 2020-01-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='elevation',
        ),
    ]
