# Generated by Django 3.0.2 on 2020-01-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations_manager', '0002_remove_target_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='elevation',
            field=models.IntegerField(default=0),
        ),
    ]
