# Generated by Django 3.0.2 on 2020-01-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations_manager', '0003_target_elevation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField()),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations_manager.Target')),
            ],
        ),
    ]
