# Generated by Django 3.0.2 on 2020-01-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations_manager', '0004_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='target_id',
        ),
        migrations.AddField(
            model_name='observation',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='observations_manager.Target'),
        ),
    ]
