# Generated by Django 3.0.2 on 2020-01-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations_manager', '0007_auto_20200121_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['-id']},
        ),
    ]
